[package]
name = "algos"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "1" }
serde = { version = "1", features = ["derive"] }
rand = "0.9.2"
byteorder = "1.5.0"
anyhow = "1.0.100"
